### ISSUE TITLE
huge file size of the compiled application.js

### ISSUE THREAD

**Issue by tawfekov** [alexferreira/ember-gen#2]
I have started to use `ember-gen` but its generated `application.js` is un compressed & un minified  sized about `1.5 MB` , its huge size to use in production , isn't it ?

1- could you please consider some options to  generate the  `application.js` in both formats ?
2- use the minified version of venders lib when generated option is minified .

thanks

**Comment by suissa** [comment]
Agree!

**Comment by alexferreira** [comment]
you can minify the application.js with the following command

```
ember-build -m
```

This command will generate the file application.min.js javascripts folder, u will need only change the index.html to the new path.

I'm working on that soon it will be more transparent.

Thank you for your feedback

**Comment by alexferreira** [comment]
If you have any questions we can reopen the issue.

I have helped.
