### ISSUE TITLE
Problems on install at NodeJs 0.10.4

### ISSUE THREAD

**Issue by herom** [alexferreira/ember-gen#3]
hey alex,
thanks a lot for this tool - I used it to see how a directory structure for a 'large' web app should look like and your tool seems to me like it's giving some good advices for further usage.

I installed ember-gen onto NodeJs 0.10.4, so it should match your requirement of min version 0.8. unfortunately, I saw several errors appear during the install and I guess this is also the reason why 'ember build' is showing errors.

here's the log, if it's of any help for you:

============ LOG START ============

npm http 200 https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/json-stringify-safe/-/json-stringify-saf
e-3.0.0.tgz
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (c:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:113:14)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:81:11
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\herom\AppData\Roaming\npm\node_modules\ember-gen\node_m
odules\jsdom\node_modules\contextify
gyp ERR! node -v v0.10.4
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok
npm http 200 https://registry.npmjs.org/qs
npm http 200 https://registry.npmjs.org/cookie-jar/-/cookie-jar-0.3.0.tgz
npm http 200 https://registry.npmjs.org/form-data/-/form-data-0.0.8.tgz
npm http 200 https://registry.npmjs.org/forever-agent/-/forever-agent-0.3.0.tgz
npm http GET https://registry.npmjs.org/qs/-/qs-0.5.6.tgz
npm WARN optional dep failed, continuing contextify@0.1.5
npm http 200 https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.3.0.tgz
npm WARN package.json forever-agent@0.3.0 No README.md file found!
npm http 200 https://registry.npmjs.org/hawk/-/hawk-0.10.2.tgz
npm http 200 https://registry.npmjs.org/json-stringify-safe/-/json-stringify-saf
e-3.0.0.tgz
npm http 200 https://registry.npmjs.org/qs/-/qs-0.5.6.tgz
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.4
","npm":"1.2.18"})
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/ctype/0.5.2
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/assert-plus/-/assert-plus-0.1.2.tgz
npm http 200 https://registry.npmjs.org/ctype/0.5.2
npm http GET https://registry.npmjs.org/ctype/-/ctype-0.5.2.tgz
npm http 200 https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/asn1/-/asn1-0.1.11.tgz
npm http 200 https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/boom/-/boom-0.3.8.tgz
npm http 200 https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/cryptiles/-/cryptiles-0.1.3.tgz
npm http 200 https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/sntp/-/sntp-0.1.4.tgz
npm http 200 https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/combined-stream/-/combined-stream-0.0.4.
tgz
npm http 200 https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/hoek/-/hoek-0.7.6.tgz
npm http 200 https://registry.npmjs.org/assert-plus/-/assert-plus-0.1.2.tgz
npm http 200 https://registry.npmjs.org/ctype/-/ctype-0.5.2.tgz
npm http 200 https://registry.npmjs.org/boom/-/boom-0.3.8.tgz
npm http 200 https://registry.npmjs.org/asn1/-/asn1-0.1.11.tgz
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/async/-/async-0.2.7.tgz
npm http 200 https://registry.npmjs.org/sntp/-/sntp-0.1.4.tgz
npm http 200 https://registry.npmjs.org/cryptiles/-/cryptiles-0.1.3.tgz
npm http 200 https://registry.npmjs.org/combined-stream/-/combined-stream-0.0.4.
tgz
npm http 200 https://registry.npmjs.org/hoek/-/hoek-0.7.6.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.2.7.tgz
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.4"
,"npm":"1.2.18"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"v0.
10.4","npm":"1.2.18"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.4"
,"npm":"1.2.18"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.4"
,"npm":"1.2.18"})
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 200 https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/delayed-stream/-/delayed-stream-0.0.5.tg
z
npm http 200 https://registry.npmjs.org/delayed-stream/-/delayed-stream-0.0.5.tg
z
C:\Users\herom\AppData\Roaming\npm\ember -> C:\Users\herom\AppData\Roaming
\npm\node_modules\ember-gen\bin\ember
ember-gen@0.1.0 C:\Users\herom\AppData\Roaming\npm\node_modules\ember-gen
├── fleck@0.5.1
├── commander@1.1.1 (keypress@0.1.0)
├── browserbuild@0.6.0 (commander@0.5.2, debug@0.6.0)
├── rsvp-that-works@1.2.0
├── fs-extra@0.5.0 (jsonfile@0.0.1, ncp@0.2.7, mkdirp@0.3.5, rimraf@2.1.4)
├── uglify-js@2.2.5 (source-map@0.1.22, optimist@0.3.7)
├── walk@2.2.1 (forEachAsync@2.2.0)
├── handlebars@1.0.8 (optimist@0.3.7, uglify-js@1.2.6)
├── cli-color@0.2.1 (es5-ext@0.9.2, memoizee@0.2.4)
├── findit@0.1.2 (seq@0.3.5)
└── jsdom@0.3.4 (cssom@0.2.5, nwmatcher@1.3.1, htmlparser@1.7.6, cssstyle@0.2.3,
 request@2.20.0)

herom@devmachine /c/Source/_EXPERIMENTS/EmberJS
$ ember new demo-app -t bootstrap
-> Creating application files and directories
   created:     demo-app
   created:     demo-app/controllers
   created:     demo-app/models
   created:     demo-app/routes
   created:     demo-app/templates
   created:     demo-app/helpers
   created:     demo-app/views
   created:     demo-app/mixins
   created:     demo-app/.ember
   created:     demo-app/index.html
   created:     demo-app/templates/application.hbs
   created:     demo-app/functions.js
   created:     demo-app/templates/index.hbs
   created:     demo-app/app.js
   created:     demo-app/store.js
   created:     demo-app/routes.js
   created:     demo-app/vendor
   created:     demo-app/vendor/ember-easyform.js
   created:     demo-app/vendor/ember-validations.js
   created:     demo-app/vendor/localstorage_adapter.js
   created:     demo-app/vendor/ember-data.js
   created:     demo-app/vendor/underscore.js
   created:     demo-app/vendor/handlebars.js
   created:     demo-app/vendor/jquery.js
   created:     demo-app/vendor/ember.js
   created:     demo-app/stylesheets
   created:     demo-app/stylesheets/app.css
   created:     demo-app/stylesheets/bootstrap-responsive.css
   created:     demo-app/stylesheets/bootstrap.css
   created:     demo-app/javascripts

herom@devmachine /c/Source/_EXPERIMENTS/EmberJS
$ cd demo-app/

herom@devmachine /c/Source/_EXPERIMENTS/EmberJS/demo-app
$ ls -l
total 6
-rw-r--r--    1 herom Administ       46 Apr 25 07:13 app.js
drwxr-xr-x    1 herom Administ        0 Apr 25 07:13 controllers
-rw-r--r--    1 herom Administ        0 Apr 25 07:13 functions.js
drwxr-xr-x    1 herom Administ        0 Apr 25 07:13 helpers
-rw-r--r--    1 herom Administ      534 Apr 25 07:13 index.html
drwxr-xr-x    1 herom Administ        0 Apr 25 07:13 javascripts
drwxr-xr-x    1 herom Administ        0 Apr 25 07:13 mixins
drwxr-xr-x    1 herom Administ        0 Apr 25 07:13 models
drwxr-xr-x    1 herom Administ        0 Apr 25 07:13 routes
-rw-r--r--    1 herom Administ       63 Apr 25 07:13 routes.js
-rw-r--r--    1 herom Administ      253 Apr 25 07:13 store.js
drwxr-xr-x    1 herom Administ     4096 Apr 25 07:13 stylesheets
drwxr-xr-x    1 herom Administ        0 Apr 25 07:13 templates
drwxr-xr-x    1 herom Administ     4096 Apr 25 07:13 vendor
drwxr-xr-x    2 herom Administ        0 Apr 25 07:13 views

herom@devmachine /c/Source/_EXPERIMENTS/EmberJS/demo-app
$ ember generate -s contact title:string email:string age:number
   created:     ./routes.js
   created:     ./models/contact.js
   created:     ./controllers/contacts/edit_controller.js
   created:     ./routes/contacts/new_route.js
   created:     ./routes/contacts/index_route.js
   created:     ./templates/contacts/edit.hbs
   created:     ./controllers/contacts/new_controller.js
   created:     ./controllers/contacts/show_controller.js
   created:     ./templates/contacts/show.hbs
   created:     ./templates/contacts/index.hbs

herom@devmachine /c/Source/_EXPERIMENTS/EmberJS/demo-app
$ ember build

c:\Users\herom\AppData\Roaming\npm\node_modules\ember-gen\node_modules\jsdom\
lib\jsdom.js:178
    features   = JSON.parse(JSON.stringify(window.document.implementation._fea
                                                          ^
TypeError: Cannot read property 'implementation' of undefined
    at processHTML (c:\Users\herom\AppData\Roaming\npm\node_modules\ember-gen
\node_modules\jsdom\lib\jsdom.js:178:59)
    at Object.exports.env.exports.jsdom.env (c:\Users\herom\AppData\Roaming\n
pm\node_modules\ember-gen\node_modules\jsdom\lib\jsdom.js:269:5)
    at precompile (c:\Users\herom\AppData\Roaming\npm\node_modules\ember-gen\
src\util\precompile.js:23:9)
    at c:\Users\herom\AppData\Roaming\npm\node_modules\ember-gen\src\util\pre
compile.js:10:5
    at Walker.<anonymous> (c:\Users\herom\AppData\Roaming\npm\node_modules\em
ber-gen\src\util\precompile.js:57:5)
    at Walker.EventEmitter.emit (events.js:92:17)
    at Walker._wNext (c:\Users\herom\AppData\Roaming\npm\node_modules\ember-g
en\node_modules\walk\walk.js:212:8)
    at Walker._wNext (c:\Users\herom\AppData\Roaming\npm\node_modules\ember-g
en\node_modules\walk\walk.js:210:19)
    at Walker._wNext (c:\Users\herom\AppData\Roaming\npm\node_modules\ember-g
en\node_modules\walk\walk.js:210:19)
    at Walker._wOnEmitDone (c:\Users\herom\AppData\Roaming\npm\node_modules\e
mber-gen\node_modules\walk\walk.js:109:8)

herom@devmachine /c/Source/_EXPERIMENTS/EmberJS/demo-app
$ ls -l
total 6
-rw-r--r--    1 herom Administ       46 Apr 25 07:13 app.js
drwxr-xr-x    1 herom Administ        0 Apr 25 07:14 controllers
-rw-r--r--    1 herom Administ        0 Apr 25 07:13 functions.js
drwxr-xr-x    1 herom Administ        0 Apr 25 07:13 helpers
-rw-r--r--    1 herom Administ      534 Apr 25 07:13 index.html
drwxr-xr-x    1 herom Administ        0 Apr 25 07:13 javascripts
drwxr-xr-x    1 herom Administ        0 Apr 25 07:13 mixins
drwxr-xr-x    1 herom Administ        0 Apr 25 07:14 models
drwxr-xr-x    1 herom Administ        0 Apr 25 07:14 routes
-rw-r--r--    1 herom Administ      392 Apr 25 07:14 routes.js
-rw-r--r--    1 herom Administ      253 Apr 25 07:13 store.js
drwxr-xr-x    1 herom Administ     4096 Apr 25 07:13 stylesheets
drwxr-xr-x    1 herom Administ        0 Apr 25 07:14 templates
drwxr-xr-x    1 herom Administ     4096 Apr 25 07:13 vendor
drwxr-xr-x    2 herom Administ        0 Apr 25 07:13 views

============ LOG END============

**Comment by alexferreira** [comment]
thanks for the feedback, I'll check what's going on with version 10.0.4 node

**Comment by alexferreira** [comment]
herom I'm running on my machine with node and npm v1.2.18 v10.0.4 and am not finding this problem.

I tested the `ember-gen` in mac os x and linux, you got to try on some virtual machines with linux?

**Comment by herom** [comment]
alexferreira sorry, I forgot to mention that I'm here at work and using a Windows 7 Professional 64bit SP1 and unfortunately I have no virtual machines at hand - will give it a try in my spare time at home at my linux machine..

**Comment by alexferreira** [comment]
Heron, I'll raise a virtual machine with windows 7 to test, I believe that with linux will not have difficulty using.

I believe that by next week I release a new version with some interesting features, some are already in the business dev others still in development.

I hope you enjoy the project.

**Comment by kaiquewdev** [comment]
Check your python enviroment variable.

http://docs.python.org/2/using/windows.html

**Comment by kaiquewdev** [comment]
And re-install the node or just node-gyp.

**Comment by rskumar** [comment]
I too have Windows 7 64-Bit, installed node http://nodejs.org/dist/v0.10.17/node-v0.10.17-x86.msi and later tested with 64 bit build too.
When I run command nodejs --version it shows 

``` cmd
C:\Users\ravi>node --version
v0.8.12
```

Something is messed up in win distribution.

**Comment by kaiquewdev** [comment]
Try to update your nodejs and put an report more specific of your problem,
into this issue.
Em 04/09/2013 14:22, "Ravi" notifications@github.com escreveu:

**Comment by kaiquewdev** [comment]
but the ember-gen it's correctly working now?
