### ISSUE TITLE
bump ember to RC3

### ISSUE THREAD

**Issue by alexferreira** [alexferreira/ember-gen#8]

**Comment by YomeKatsuma** [comment]
Hi Alex,

I've try to change the ember.js and handlebars.js in the 'vendor' folder (the lastest version). I rebuilt the application, but chrome raise an error : 

Uncaught Error: failed to require "handlebars" from undefined application.js:1
require application.js:1
(anonymous function) application.js:1
slice application.js:56936
(anonymous function) application.js:57115
require.register.Handlebars application.js:66749
require application.js:1
(anonymous function) application.js:1
require.register.DS.Model.extend.name application.js:87
require application.js:1
(anonymous function) application.js:82597
(anonymous function)

Is there anything i've lost (i.e. only changing js files in the vendor folder does not enough) ?

Cheer,

**Comment by YomeKatsuma** [comment]
Alex,

Mea culpa, i was trying to compile with handlebars rc.4 which is not yet managed by ember rc.3

Cheer.

(closable issue)

**Comment by alexferreira** [comment]
ok ;)
